### ISSUE TITLE
Raspbian NPM issue. 

### ISSUE THREAD

**Issue by hiimthetwos** [brannondorsey/chattervox#15]
NPM fails to install. 

(node:1185) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.62-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/chattervox
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/chattervox/npm-debug.log
npm ERR! not ok code 0

**Comment by brannondorsey** [comment]
Thanks for the bug report! It looks like you've got an ancient version of npm that is no longer supported. You've got version 1.4.21 but my recent version is ~6.4.1. You *may* be able to update npm using npm itself, if your version isn't too out of date to do that:

```bash
# this may need sudo depending on your configuration
npm install -g npm 
```
If that doesn't work, you should re-install npm (and maybe node + npm) from the official releases. I actually manage (and recommend) my node / npm versions via [nvm](https://github.com/creationix/nvm). It's served me very well for years.
