### ISSUE TITLE
Either handle config loading from cli nicely, or remove it.

### ISSUE THREAD

**Issue by brannondorsey** [brannondorsey/chattervox#4]
```
chattervox --config ~/Documents/code/pw/README.md chat
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.load (/home/braxxox/.nvm/versions/node/v8.12.0/lib/node_modules/chattervox/build/config.js:43:17)
    at /home/braxxox/.nvm/versions/node/v8.12.0/lib/node_modules/chattervox/build/main.js:104:29
    at Generator.next (<anonymous>)
    at /home/braxxox/.nvm/versions/node/v8.12.0/lib/node_modules/chattervox/build/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/braxxox/.nvm/versions/node/v8.12.0/lib/node_modules/chattervox/build/main.js:4:12)
    at main (/home/braxxox/.nvm/versions/node/v8.12.0/lib/node_modules/chattervox/build/main.js:90:12)
    at Object.<anonymous> (/home/braxxox/.nvm/versions/node/v8.12.0/lib/node_modules/chattervox/build/main.js:127:1)
    at Module._compile (module.js:653:30)
```

**Comment by brannondorsey** [comment]
Closed with v0.3.0.
